// Machine-checkable rules derived from the APM policies in policies/.
// Each rule states: when it applies (scope), how to test a document, what compensating
// controls the policy itself accepts, and what to change to become compliant.
//
// test.kind:
//   numeric     extract number+unit near a keyword, compare against maxDays
//   mustState   if in scope, the document MUST contain one of these patterns
//   mustNotSay  if the document contains this, it conflicts with the policy
//   pairing     document says A but must also say B
window.COMPLIANCE_RULES = [

// ---------- Cryptography and Key Management Standard (09.03.027-5.0) ----------
{ id:'CRY-01', doc:'Cryptography and Key Management Standard', clause:'\u00a75 key rotation table', cat:'Cryptography',
  title:'Key rotation maximum age',
  requires:'Production internet-facing or production data: 60 days. Production not internet-facing: 90 days. Non-production internet-facing: 90 days. Non-production: 180 days.',
  scope:/key vault|keyvault|secret|rotat(e|ion)|cryptographic key|private key/i,
  test:{ kind:'numeric', near:/rotat/i, maxDays:60 },
  compensating:['published by design','displayed on the .{0,20}lock screen','device-bound','bound .{0,30}conditional access','no corporate (data|information)','single device','one physical'],
  remedy:'Obtain a CISO ruling that account credentials are governed by the Identity and IT Access Management Standard rather than \u00a75 keying material, OR record an accepted risk in the RFFR SoA with the blast-radius argument, OR shorten the rotation interval to 60 days.' },

{ id:'CRY-02', doc:'Cryptography and Key Management Standard', clause:'\u00a74.1 approved algorithms', cat:'Cryptography',
  title:'Minimum key sizes for approved algorithms',
  requires:'AES 128 min (256 preferred, never ECB). RSA 2048 min (3072 preferred). ECC/ECDH/ECDSA \u2265224 bits. SHA-256/384/512. DH 2048 min, ephemeral only.',
  scope:/\b(rsa|aes|sha-?\d|ecdsa|ecdh|elliptic curve|diffie)\b/i,
  test:{ kind:'mustNotSay', pattern:/\b(rsa[- ]?1024|aes[- ]?64|sha-?1\b|md5|\bdes\b|3des|rc4|ecb mode)\b/i, guard:/encrypt|cipher|algorithm|hash|key size|signing|tls|certificate|cryptograph/i, window:180 },
  compensating:[],
  remedy:'Replace any algorithm below the approved minimum. State the actual algorithm and key size in a settings table rather than leaving it to platform defaults.' },

{ id:'CRY-03', doc:'Cryptography and Key Management Standard', clause:'\u00a75 PKI', cat:'Cryptography',
  title:'Wildcard certificates must not be used',
  requires:'Due to increased risk, wildcard certificates must not be used.',
  scope:/certificate|x\.509|pki|tls/i,
  test:{ kind:'mustNotSay', pattern:/wildcard certificate|\*\.[a-z0-9-]+\.[a-z]{2,}/i, guard:/certificate|cert\b|x\.509|\bpki\b|issued by|certificate authority/i, window:150 },
  compensating:[],
  remedy:'Replace the wildcard certificate with per-host certificates. Public-facing services use a commercial trusted CA; internal services use APM PKI.' },

{ id:'CRY-04', doc:'Cryptography and Key Management Standard', clause:'\u00a74.2 TLS cipher suites', cat:'Cryptography',
  title:'TLS version and cipher suite must be stated and approved',
  requires:'TLS 1.2 (16 named suites) or TLS 1.3 (4 named suites). Anonymous DH not permitted. Ephemeral variants only.',
  scope:/tls|https|mtls|mutual tls|cipher/i,
  test:{ kind:'mustState', pattern:/tls ?1\.[23]|tls_?(aes|ecdhe|dhe)/i },
  compensating:[],
  remedy:'State the TLS version and the approved cipher suite list from \u00a74.2 explicitly, rather than relying on platform defaults. Confirm TLS 1.0/1.1 are disabled.' },

{ id:'CRY-05', doc:'Cryptography and Key Management Standard', clause:'\u00a73 Authorisation', cat:'Cryptography',
  title:'Certificate issuance requires D&T Operations approval recorded in ITSM',
  requires:'X.509 certificates and keying material must be requested and approved by the D&T Operations team, with the request recorded in the IT Service Management application.',
  scope:/certificate|scep|cloud pki|x\.509|code[- ]signing/i,
  test:{ kind:'mustState', pattern:/d&t operations|service management|itsm|servicenow|snow ticket|approved by .{0,40}operations/i },
  compensating:[],
  remedy:'Add a line naming D&T Operations as the approver for certificate issuance and stating that the request is recorded in the ITSM tool.' },

{ id:'CRY-06', doc:'Cryptography and Key Management Standard', clause:'\u00a74.4 encryption in transit', cat:'Cryptography',
  title:'Internal and above must be encrypted in transit on every network',
  requires:'Internal, Confidential and Restricted MUST use current ASD approved encryption over public/guest, corporate and secured networks alike.',
  scope:/in transit|transmit|network|traffic|egress/i,
  test:{ kind:'mustState', pattern:/encrypt|tls|https|ipsec|asd approved/i },
  compensating:[],
  remedy:'State the transit encryption for every documented data path, including internal/corporate hops - the standard makes no exemption for corporate networks.' },

// ---------- Windows SOE Hardening Standard V3.0 ----------
{ id:'SOE-01', doc:'Windows SOE Hardening Standard V3.0', clause:'Win11 OS baseline - Min Device Password Length', cat:'Endpoint & SOE',
  title:'Minimum device password length is 14 characters',
  requires:'Min Device Password Length = 14.',
  scope:/passphrase|password|credential/i,
  test:{ kind:'numeric', near:/(passphrase|password|credential|minimum device password)/i, minChars:14 },
  compensating:[],
  remedy:'Constrain the generator so every credential is at least 14 characters and state the guaranteed minimum, not an approximate length.' },

{ id:'SOE-02', doc:'Windows SOE Hardening Standard V3.0', clause:'Win11 OS baseline - PowerShell Execution Policy', cat:'Endpoint & SOE',
  title:'PowerShell execution policy allows only signed scripts',
  requires:'Execution Policy (Device) = Allow only signed scripts, with script block logging enabled.',
  scope:/powershell|\.ps1|script|remediation|runbook/i,
  test:{ kind:'mustState', pattern:/signed|code[- ]signing|signature/i },
  compensating:[],
  remedy:'State that every device-side script is signed with the APM code-signing certificate, and name the certificate dependency as a build prerequisite.' },

{ id:'SOE-03', doc:'Windows SOE Hardening Standard V3.0', clause:'USB Baseline - removable storage', cat:'Endpoint & SOE',
  title:'Removable storage is deny-all by default',
  requires:'All Removable Storage classes: Deny all access = Enabled. Removable Disks: Deny write access = Enabled. BitLocker requires encryption on removable drives.',
  scope:/usb|removable|external drive|thumb drive/i,
  test:{ kind:'mustNotSay', pattern:/(deny write access[^.]{0,40}(disable|not configured)|removable[^.]{0,30}(enabled|permitted|allowed)|usb (storage )?(enabled|permitted|allowed))/i },
  compensating:['autoplay','autorun','scan removable','block untrusted and unsigned processes','app ?control','application control','file explorer[^.]{0,40}removable','explicit approval','exception polic'],
  remedy:'Removable media is administratively disabled by default under the Posture Statement \u00a74.3 with an explicit-approval path. Deliver the exception by assignment (exclude the device group from the estate USB baseline and assign a purpose-built exception profile), record the compensating controls, and cite the \u00a74.3 approval clause plus who granted it.' },

{ id:'SOE-04', doc:'Windows SOE Hardening Standard V3.0', clause:'App Control for Business', cat:'Endpoint & SOE',
  title:'Application control must be enforced, and script enforcement is an open estate gap',
  requires:'App Control Audit and Enforced policies, 18 trusted signers. Script Enforcement is DISABLED estate-wide and flagged in the standard for attention.',
  scope:/app ?control|application control|wdac|allow[- ]?list|executable/i,
  test:{ kind:'mustState', pattern:/script enforcement|enforced|enforce/i },
  compensating:['asr','attack surface reduction','assigned access','no shell'],
  remedy:'If application control is cited as a compensating control, enable script enforcement in the design variant - the estate policies have it off, so App Control alone does not constrain scripts carried in on removable media.' },

{ id:'SOE-05', doc:'Windows SOE Hardening Standard V3.0', clause:'Win11 OS baseline - remote access', cat:'Endpoint & SOE',
  title:'Remote Assistance, Remote Shell and inbound RDP are disabled',
  requires:'Configure Offer/Solicited Remote Assistance = Disabled. Allow Remote Shell Access = Disabled. Allow users to connect remotely using Remote Desktop Services = Disabled.',
  scope:/remote (support|access|assistance|desktop|shell)|teamviewer|anydesk|vnc|screen ?share/i,
  test:{ kind:'mustNotSay', pattern:/teamviewer|anydesk|\bvnc\b|logmein|splashtop/i },
  compensating:['attended','consent','mfa|multi-factor','per-device','file transfer disabled','session log','sentinel'],
  remedy:'Prefer an approved path (Intune Remote Help or Defender live response), which removes the variation. If a third-party tool is retained, document the full access model and obtain explicit CISO acceptance as a variation to the estate remote-access position.' },

{ id:'SOE-06', doc:'Windows SOE Hardening Standard V3.0', clause:'Win11 OS baseline - Block user from showing account details on sign-in', cat:'Endpoint & SOE',
  title:'Account details must not be shown on the sign-in screen',
  requires:'Block user from showing account details on sign-in = Enabled. Lock screen further hardened (no camera, no slide show, no app notifications).',
  scope:/lock screen|sign-?in screen|logon screen|wallpaper/i,
  test:{ kind:'mustNotSay', pattern:/(display|show|shown|shows)[^.]{0,60}(credential|passphrase|password|upn)/i, guard:/lock screen|sign-?in|logon|wallpaper/i, window:200 },
  compensating:['per-device','device-bound','conditional access','unusable','no corporate','rotated'],
  remedy:'Record as an argued deviation naming both this control and the clear desk and screen policy in the Posture Statement \u00a74.1, with the reason a displayed credential is safe here and the reason autologon was rejected. Obtain APM Cyber Security acceptance.' },

{ id:'SOE-07', doc:'Windows SOE Hardening Standard V3.0', clause:'Windows compliance policy', cat:'Endpoint & SOE',
  title:'Compliance policy must carry the nine device-health gates',
  requires:'BitLocker, Secure Boot, Firewall, TPM, Antivirus, Antispyware, Defender Antimalware, security intelligence up to date, real-time protection - all Required.',
  scope:/compliance polic/i,
  test:{ kind:'pairing', a:/compliance polic/i, b:/secure boot/i },
  compensating:[],
  remedy:'Mirror all nine staff gates in the design compliance policy. The standard records no minimum OS version as an open observation - closing it in your design exceeds the standard.' },

{ id:'SOE-08', doc:'Windows SOE Hardening Standard V3.0', clause:'Win11 OS baseline - Interactive Logon Machine Inactivity Limit', cat:'Endpoint & SOE',
  title:'Machine inactivity limit is 900 seconds',
  requires:'Interactive Logon Machine Inactivity Limit = 900.',
  scope:/inactiv|idle|timeout|sign-?out/i,
  test:{ kind:'numeric', near:/(inactiv|idle|timeout)/i, maxSeconds:900 },
  compensating:[],
  remedy:'Set the inactivity limit to 900 seconds or lower. A shorter limit exceeds the standard and should be stated as such.' },

// ---------- Cyber Security Posture Statement (09.01.033-5.0) ----------
{ id:'POS-01', doc:'Cyber Security Posture Statement', clause:'\u00a74.2 Data Centres', cat:'Governance',
  title:'Data residency is Microsoft Australian Azure - Sydney and Melbourne',
  requires:'All data held on APM managed infrastructure is stored in Microsoft Australian Azure, Sydney and Melbourne data centres.',
  scope:/azure|region|data cent|residency|tenant/i,
  test:{ kind:'mustNotSay', pattern:/\b(east us|west us|west europe|north europe|southeast asia|east asia|uk south|central us|australia central)\b/i, guard:/region|deploy|host|data cent|azure/i, window:180 },
  compensating:[],
  remedy:'Host in Australia East (Sydney) or Australia Southeast (Melbourne) and state the region explicitly. Any other region breaches the stated residency position.' },

{ id:'POS-02', doc:'Cyber Security Posture Statement', clause:'\u00a74.3 Enterprise Asset Management', cat:'Governance',
  title:'Removable media requires explicit APM ICT stakeholder approval',
  requires:'Access to removable media is administratively disabled on APM ICT assets. Explicit approval must be granted by APM ICT stakeholder(s) to allow access to APM approved removable media.',
  scope:/usb|removable/i,
  test:{ kind:'mustState', pattern:/explicit approval|approved by|exception polic|accepted risk|approval[^.]{0,30}(granted|obtained)/i },
  compensating:[],
  remedy:'Cite this clause as the policy basis for the exception and record who granted the explicit approval and when. This converts the USB position from a defence into a citation.' },

{ id:'POS-03', doc:'Cyber Security Posture Statement', clause:'\u00a76.2 Remote Access', cat:'Governance',
  title:'Remote access requires APM VPN or approved VDI',
  requires:'All remote access to the APM network requires APM VPN, or approval to use its VDI. Services monitored during use; all connections encrypted.',
  scope:/remote access|remote support|vpn|vdi/i,
  test:{ kind:'mustState', pattern:/vpn|virtual desktop|vdi|avd|approved|variation|accepted/i },
  compensating:['monitored','encrypted','mfa|multi-factor','session log'],
  remedy:'Use VPN or approved VDI, or document the alternative as an approved variation with monitoring and encryption evidence.' },

{ id:'POS-04', doc:'Cyber Security Posture Statement', clause:'\u00a75.2 Identity and Access Management', cat:'Identity & Access',
  title:'MFA, ISM-aligned complex passwords, inactivity session termination',
  requires:'Aligned to the Identity and IT Access Management Standard: MFA, complex passwords aligned to ISM, session termination based on inactivity, need-to-know and least-privilege.',
  scope:/authenticat|sign-?in|identity|account|mfa/i,
  test:{ kind:'mustState', pattern:/mfa|multi-factor|passwordless|phishing-resistant|conditional access|compensating/i },
  compensating:['conditional access','device-bound','compliant device','cannot satisfy','compensating control'],
  remedy:'Where MFA cannot be satisfied (fixed-credential service accounts), state that explicitly and set out the compensating controls that replace the possession factor. Do not leave MFA unaddressed.' },

{ id:'POS-05', doc:'Cyber Security Posture Statement', clause:'\u00a74.1 Physical Security', cat:'Governance',
  title:'Clear desk and clear screen policy is enforced',
  requires:'Clear desk and screen policy enforced through the Information Security Code of Practice.',
  scope:/screen|display|kiosk|wallpaper|lock screen/i,
  test:{ kind:'mustNotSay', pattern:/(display|show)[^.]{0,50}(password|passphrase|credential)/i, guard:/screen|display|kiosk|wallpaper/i, window:200 },
  compensating:['per-device','device-bound','no corporate','rotated','conditional access'],
  remedy:'If information is deliberately displayed on screen, argue it against this clause explicitly rather than leaving the contradiction to be found in review.' },

// ---------- Continuous Monitoring Plan (09.03.021-5.0) ----------
{ id:'MON-01', doc:'Continuous Monitoring Plan', clause:'Penetration Testing', cat:'Monitoring',
  title:'Penetration testing prior to go-live, after material change, and annually',
  requires:'Pen testing performed prior to a system going live; after material upgrades or modifications; generally annually. System owner approval required; schedule agreed with System Owners and approved by the CISO.',
  scope:/penetration test|pen ?test|security testing/i,
  test:{ kind:'mustState', pattern:/prior to (go|going) live|before (go|going) live|pre-?production|annual/i },
  compensating:[],
  remedy:'State that penetration testing completes before the system goes live (not merely before wider rollout), name the System Owner who approves scope, and note the schedule is CISO-approved.' },

{ id:'MON-02', doc:'Continuous Monitoring Plan', clause:'Vulnerability Management', cat:'Monitoring',
  title:'Continuous vulnerability monitoring via Defender and Wiz.io',
  requires:'All APM systems are continuously monitored using Defender for Cloud and Defender for Endpoint. Wiz.io continuously monitors cloud service environments. Weekly Cyber/Digital Ops review meeting.',
  scope:/vulnerabilit|patch|monitor|defender|endpoint protection/i,
  test:{ kind:'mustState', pattern:/defender for endpoint|defender for cloud|wiz\.io|wiz\b/i },
  compensating:[],
  remedy:'Name Defender for Endpoint onboarding for every device population in the design, including any in a separate tenant, and confirm cloud resources are onboarded to Wiz.io. Cross-tenant licensing and log flow must be designed, not assumed.' },

{ id:'MON-03', doc:'Continuous Monitoring Plan', clause:'CONMON independence', cat:'Monitoring',
  title:'Assessment must be performed by personnel independent of the system',
  requires:'CONMON activities conducted by the Cyber Security Team or personnel of similar skillset independent of the system being assessed; may be internal or third party.',
  scope:/assessment|vulnerability assessment|audit|review/i,
  test:{ kind:'mustState', pattern:/independent|third party|external|cyber security team/i },
  compensating:[],
  remedy:'Name who performs the assessment and state their independence from the system owner.' },

// ---------- Cyber Incident Response Plan (09.03.005-7.0) ----------
{ id:'IRP-01', doc:'Cyber Incident Response Plan', clause:'Containment step 9 / ISM 915c', cat:'Incident Response',
  title:'Personal or sensitive data incidents are notifiable to DEWR and ASD',
  requires:'Where an incident affects an environment holding personal/sensitive data, the CIRT Manager and Data Owner notify the Department as Accreditation Authority ASAP via securitycompliancesupport@jobs.gov.au and notify ASD. No action affecting evidence integrity prior to ASD involvement (ISM 915c).',
  scope:/incident|compromis|breach|stolen|lost device|wipe|reset/i,
  test:{ kind:'mustState', pattern:/incident response plan|dewr|accreditation authority|asd|915c|notif/i },
  compensating:[],
  remedy:'Reference the Cyber Incident Response Plan and the Theft / Loss of IT Asset playbook rather than inventing a procedure. State that automated response is limited to containment (disable the account) and that device wipe must not occur before ASD clearance.' },

{ id:'IRP-02', doc:'Cyber Incident Response Plan', clause:'Reporting / Identification', cat:'Incident Response',
  title:'Incidents reported via APM Assist and logged in ServiceNow',
  requires:'All staff must immediately report a real or potential incident using APM Assist. All incidents logged in a ServiceNow ticket; P1/P2 update the Major Cyber Security Incident Register.',
  scope:/incident|alert|escalat/i,
  test:{ kind:'mustState', pattern:/apm assist|servicenow|snow|major cyber security incident register|incident manager/i },
  compensating:[],
  remedy:'Name the reporting path (APM Assist, ServiceNow) in the service management section so operational staff have a defined route.' },

{ id:'IRP-03', doc:'Cyber Incident Response Plan', clause:'Retaining evidence', cat:'Incident Response',
  title:'Network traffic logs retained 7 days prior to incident discovery',
  requires:'Network traffic logs retained for a period of seven days prior to the discovery of the incident; all retention or removal logged in the chain of custody document.',
  scope:/log retention|logging|retain|sentinel|log analytics/i,
  test:{ kind:'mustState', pattern:/\b(7|seven) days|\d+ days|\d+ ?day retention|retention/i },
  compensating:[],
  remedy:'State log retention explicitly and confirm it exceeds 7 days for network traffic. The kiosk design already states 180 days for Sentinel and ZIA, which satisfies this.' },

// ---------- Trusted Insider Program (09.03.020-6.0) ----------
{ id:'TIP-01', doc:'APM Trusted Insider Program', clause:'\u00a73.2 Identity and Access Management', cat:'Identity & Access',
  title:'Privileged administration uses separate accounts with added complexity',
  requires:'Staff performing privileged administration tasks use separate accounts with trusted insider and additional privileged account protections. Additional password complexity applied. Contractors held to the same controls.',
  scope:/privileged|administrator|admin account|elevated|local admin/i,
  test:{ kind:'mustState', pattern:/separate account|dedicated .{0,20}account|non-privileged|per-device .{0,20}account|paw|privileged access/i },
  compensating:[],
  remedy:'Name the administrative accounts, confirm they are separate from standard accounts, and state the additional complexity and monitoring applied. Contractors get the same controls.' },

{ id:'TIP-02', doc:'APM Trusted Insider Program', clause:'\u00a73.3-3.4', cat:'Identity & Access',
  title:'Enterprise password manager and Purview Insider Risk Management',
  requires:'IT Trusted Users provisioned access to an enterprise password management solution. Protective monitoring via external SOC; monitoring includes Microsoft Purview Insider Risk Management. Logging covers authentication events, endpoint protection alerts, internet browsing activity.',
  scope:/privileged|admin|password manager|credential store|insider/i,
  test:{ kind:'mustState', pattern:/password (manager|state|vault)|key vault|purview|insider risk|soc\b/i },
  compensating:[],
  remedy:'State where privileged credentials are stored (enterprise password manager or Key Vault) and confirm the population is in scope for Purview Insider Risk Management and SOC monitoring.' },

// ---------- Compliance Management Plan (09.03.055-1.2) ----------
{ id:'CMP-01', doc:'Compliance Management Plan', clause:'Statement of Applicability', cat:'Governance',
  title:'Controls and exclusions must appear in the RFFR Statement of Applicability',
  requires:'The SoA lists all Annex A controls, states applicability, justifies inclusion/exclusion and references implementation. The RFFR SoA additionally covers DEWR contractual obligations and ISM controls.',
  scope:/exclu|exception|accepted risk|not applicable|deviation|compensating/i,
  test:{ kind:'mustState', pattern:/statement of applicability|\bsoa\b|rffr/i },
  compensating:[],
  remedy:'Every exclusion or accepted risk claimed in the design must be recorded in the RFFR SoA with justification and implementation reference. Name the SoA in the design.' },

{ id:'CMP-02', doc:'Compliance Management Plan', clause:'Annual compliance calendar', cat:'Governance',
  title:'Changes to the operating environment are notifiable to DEWR within 5 days',
  requires:'Notify DEWR within 5 days of any changes to APM or subcontractor circumstances that may affect the risk profile, to enable re-categorisation.',
  scope:/new tenant|new subscription|internet-?facing|public endpoint|third party|subcontractor|new environment/i,
  test:{ kind:'mustState', pattern:/dewr|notif|5 days|five days|re-?categoris/i },
  compensating:[],
  remedy:'Where the design introduces a new tenant, a new internet-facing endpoint or a new supplier, flag the 5-day DEWR notification as an implementation task and name the owner.' },

{ id:'CMP-03', doc:'Compliance Management Plan', clause:'Governance and accountability', cat:'Governance',
  title:'Control validation quarterly; ISM updates reviewed quarterly',
  requires:'Control owners validate implementation status, details and applicability quarterly. Published ISM updates reviewed each Mar, Jun, Sep, Dec with applicability and risk analysis.',
  scope:/control owner|validation|ism|review cadence|assurance/i,
  test:{ kind:'mustState', pattern:/quarterly|control owner|ism (update|version)|annual review/i },
  compensating:[],
  remedy:'Name the control owner for each control the design introduces, and note that the design is re-checked against quarterly ISM updates.' },

// ---------- Artificial Intelligence Policy (09.01.037-2.1) ----------
{ id:'AI-01', doc:'Artificial Intelligence Policy', clause:'Approval for use of AI', cat:'Governance',
  title:'AI use requires ELT sign-off, a business case and a privacy impact assessment',
  requires:'AI use must be signed off by the ELT member for the business, with assessments by the regional Data Privacy and Digital leaders. Business case and privacy impact assessment required. Human in the loop for decision-making.',
  scope:/\b(ai|artificial intelligence|copilot|llm|generative|chatgpt|gemini|machine learning)\b/i,
  test:{ kind:'mustState', pattern:/elt|privacy impact|business case|approval|data privacy|human in the loop/i },
  compensating:['ephemeral','no corporate data','public site','category filter','job seeker'],
  remedy:'If the design permits, embeds or exposes AI, confirm with Data Privacy whether it constitutes APM use of AI requiring ELT sign-off and a privacy impact assessment. Record the outcome in the decision register.' },

{ id:'AI-02', doc:'Artificial Intelligence Policy', clause:'Ongoing governance of AI use', cat:'Governance',
  title:'Every shared AI agent or use case has a named owner and appears in the Agent register',
  requires:'Every shared AI agent, use case or deployment must have an explicitly assigned owner responsible for accuracy, relevance and maintenance. A central regional Agent register records purpose, owner and audience.',
  scope:/\b(ai agent|agent|copilot|assistant|automation with ai)\b/i,
  test:{ kind:'mustState', pattern:/owner|agent register|accountab/i },
  compensating:[],
  remedy:'Name the owner of any AI agent or use case the design creates and add it to the regional Agent register.' },

// ---------- Identity and IT Access Management Standard (09.03.035-5.0) ----------
{ id:'IAM-01', doc:'Identity and IT Access Management Standard', clause:'\u00a75 Clients Access Management', cat:'Identity & Access',
  title:'Client-use IT assets are segregated from APM IT systems and store no client information',
  requires:'Client systems must not be connected to any non-public APM IT systems. No information created by the client is stored on the asset. Clients receive acceptable-use guidelines. APM employees must not use client-designated assets for APM duties.',
  scope:/participant|job ?seeker|client (device|system|computer|kiosk)|public[- ]area|kiosk/i,
  test:{ kind:'mustState', pattern:/not connect|blocked|cannot (access|reach)|segregat|isolat|no (corporate|apm) (data|information|system)|purge|deleted (on|at|every)/i },
  compensating:[],
  remedy:'State how the fleet is disconnected from non-public APM systems (CA block, network segregation), how client-created information is destroyed, and where the participant acceptable-use guidance lives. This clause is also the policy basis for exempting client assets from staff-user controls - cite it when arguing a deviation.' },

{ id:'IAM-02', doc:'Identity and IT Access Management Standard', clause:'\u00a74.1 / \u00a74.2.2 shared and generic accounts', cat:'Identity & Access',
  title:'Shared or generic accounts need an approved business justification and an allocation record',
  requires:'Shared user IDs avoided unless business justification approved by the Cyber Security Team; never for sensitive applications. Generic accounts get minimum rights, no corporate-system access, a process identifying the user, password reset on membership change and at 12 months.',
  scope:/shared account|generic account|session account|kiosk account|communal|walk-?up/i,
  test:{ kind:'mustState', pattern:/business justification|approved by[^.]{0,40}cyber|one account per device|per-?device account|device-bound|no corporate|minimum rights|standard (local )?user/i },
  compensating:[],
  remedy:'Record the Cyber-approved justification for the shared/anonymous account, keep it out of corporate systems, and state the per-device binding (or allocation record) that substitutes for user identification.' },

{ id:'IAM-03', doc:'Identity and IT Access Management Standard', clause:'\u00a74.1.2 Multi-Factor Authentication (ISM-0417)', cat:'Identity & Access',
  title:'Single-factor authentication requires a minimum of 15 characters',
  requires:'MFA authenticates all Users. Where a system cannot support MFA, single-factor authentication requires a minimum of 15 characters.',
  scope:/single[- ]factor|cannot support (mfa|multi-factor)|no mfa|without mfa|password-only/i,
  test:{ kind:'numeric', near:/single[- ]factor|password|credential/i, minChars:15, notNear:/standard sets|minimum device password|hardening standard|complexity categor|standard user|policy minimum/i },
  compensating:[],
  remedy:'Raise any single-factor credential to 15+ characters, or implement MFA. State the guaranteed minimum.' },

{ id:'IAM-04', doc:'Identity and IT Access Management Standard', clause:'\u00a74.2.2 System Administrator \u00b68-9', cat:'Identity & Access',
  title:'Local administrator passwords, including LAPS-managed, are at least 30 characters and rotate every 30 days',
  requires:'Default system administrator account passwords automatically changed every 30 days using LAPS. Passwords for Local Administrator accounts, including those managed by LAPS, must be at least 30 characters. Distinct per device. Guest disabled.',
  scope:/\blaps\b|local admin/i,
  test:{ kind:'numeric', near:/laps|local administrator|admin/i, minChars:30, notNear:/standard sets|minimum device password|hardening standard|policy minimum|account-name limit/i },
  compensating:[],
  remedy:'Set the LAPS policy PasswordLength to 30 or more and the rotation period to 30 days, and state both values in the settings table.' },

{ id:'IAM-05', doc:'Identity and IT Access Management Standard', clause:'\u00a74.3 User Account Locks', cat:'Identity & Access',
  title:'Accounts lock after five failed logon attempts',
  requires:'User accounts automatically locked after five failed logon attempts; unlocked only after the administrator proves the user\u2019s identity.',
  scope:/lockout|failed (logon|login|sign-?in)|brute[- ]force/i,
  test:{ kind:'mustState', pattern:/\b(five|5)\b[^.]{0,30}(failed|attempts)|lockout threshold|account lockout/i },
  compensating:['no password|credential (is |)known to no|autologon|automatic logon'],
  remedy:'State the lockout threshold (5) in the baseline table, or state why no lockable credential exists.' },

{ id:'IAM-06', doc:'Identity and IT Access Management Standard', clause:'\u00a74.2.5 Account Deactivation', cat:'Identity & Access',
  title:'Accounts deactivate same-day on termination and after 30 days of inactivity',
  requires:'On termination, the account is deactivated across all IT systems the same day the relationship ends. Accounts may also be deactivated on suspected malicious activity or after more than 30 days of inactivity.',
  scope:/deprovision|termination|leaver|offboard|account (deactivat|disabl|lifecycle)/i,
  test:{ kind:'mustState', pattern:/same day|30 days|inactivity|disabled (on|when|at)/i },
  compensating:[],
  remedy:'State the deactivation trigger and timing for every account class the design creates, including service and support accounts.' },

{ id:'IAM-07', doc:'Identity and IT Access Management Standard', clause:'\u00a74.4 Application Management', cat:'Identity & Access',
  title:'Application-control hash, publisher and path rules are validated annually',
  requires:'Cryptographic hash rules, publisher certificate rules and path rules used for application control are validated annually. Standard users cannot uninstall or disable approved software. Unauthorised access to the authoritative software source is prevented.',
  scope:/app ?control|application control|wdac|allow[- ]?list/i,
  test:{ kind:'mustState', pattern:/annual|yearly|validated|review(ed)? (at least|every)/i },
  compensating:[],
  remedy:'Add an annual validation of the App Control signer/hash/path rules to the service management calendar and name its owner.' },

{ id:'IAM-08', doc:'Identity and IT Access Management Standard', clause:'\u00a74.2.2 Service Accounts', cat:'Identity & Access',
  title:'Service accounts are managed identities or gMSA where possible, 30+ characters when interactive, with a named owner',
  requires:'Service accounts created as group Managed Service Accounts, Virtual Accounts or Managed Identities where possible. Interactive service accounts (user objects) should have 30+ character passwords, changed on compromise indicators and at 12 months. Minimum permissions. Every service account has an owner.',
  scope:/service account|automation account|service principal|managed identity|workload identity/i,
  test:{ kind:'mustState', pattern:/managed identit|gmsa|group managed|virtual account|owner/i },
  compensating:[],
  remedy:'Prefer a managed identity (no credential); otherwise state the 30-character minimum, the rotation triggers and the named owner for each service account.' },

// ---------- Intrusion Detection and Prevention Standard (09.03.034-3.0) ----------
{ id:'IDPS-01', doc:'Intrusion Detection and Prevention Standard', clause:'\u00a72 Host based Intrusion Detection', cat:'Monitoring',
  title:'EDR is mandatory on end user devices',
  requires:'Endpoint Detection and Response technology must detect and prevent threats on end user devices: anti-malware, anti-spyware, behaviour analysis, rootkit and anomaly detection in a cloud-managed platform, plus a cloud heuristic engine for unknown strains.',
  scope:/endpoint|device (fleet|population)|workstation|laptop|kiosk|soe\b/i,
  test:{ kind:'mustState', pattern:/defender for endpoint|\bedr\b|endpoint detection|\bmde\b/i },
  compensating:[],
  remedy:'Onboard every device population to Defender for Endpoint (or the approved EDR) and state the licence that carries it.' },

{ id:'IDPS-02', doc:'Intrusion Detection and Prevention Standard', clause:'\u00a72 Host based Intrusion Detection \u00b63', cat:'Monitoring',
  title:'End-user web traffic is inspected, logged and alerted',
  requires:'For End User Computing devices, web traffic must be inspected, logged and alerted upon, with detection for malware, known malicious hosts, botnet and C2 infrastructure.',
  scope:/web (traffic|filtering|access)|internet access|browsing|url filter/i,
  test:{ kind:'mustState', pattern:/zscaler|inspect|url filter|ssl inspect|proxy|web filter/i },
  compensating:[],
  remedy:'Name the web-inspection layer (Zscaler at APM), its logging destination and who receives the alerts.' },

{ id:'IDPS-03', doc:'Intrusion Detection and Prevention Standard', clause:'\u00a72 Email Gateways \u00b63', cat:'Monitoring',
  title:'Webmail is blocked at APM - email only through Outlook on APM devices',
  requires:'All webmail is blocked at APM; email may only be accessed through the approved mail application (Microsoft Outlook) on APM devices, to maintain data control and limit loss through third-party email applications.',
  scope:/webmail|personal (e-?)?mail|gmail|hotmail|outlook\.com/i,
  test:{ kind:'mustNotSay', pattern:/(webmail|personal (e-?)?mail|gmail|hotmail)[^.]{0,80}(allow|permit|open|reachable|accessible|stays open|remains? (open|reachable))/i, guard:/mail/i, window:160 },
  compensating:['client (device|system|asset)','participant','job ?seeker','not connected to[^.]{0,40}apm it systems','no (apm|corporate) (data|mailbox|account)','clients access management'],
  remedy:'Webmail on an APM staff device conflicts with this standard outright. On a client-designated asset, argue the Identity and IT Access Management Standard \u00a75 carve-out explicitly: the device is not connected to APM IT systems, holds no corporate mailbox, and the user is a client, not a User.' },

{ id:'IDPS-04', doc:'Intrusion Detection and Prevention Standard', clause:'\u00a72 Reporting and responding / Log and event correlation', cat:'Monitoring',
  title:'Logs and alerts flow to the 24/7 external SOC and the SIEM',
  requires:'Logs and alerts from APM devices go to the external 24/7 SOC. Host-based intrusion prevention alerts the APM Cyber Security Team directly. A SIEM correlates alerts and events from endpoints and gateways.',
  scope:/siem|sentinel|\bsoc\b|security operations|alert/i,
  test:{ kind:'mustState', pattern:/sentinel|siem|\bsoc\b|security operations centre?/i },
  compensating:[],
  remedy:'Route every telemetry source the design creates into Sentinel and state which alerts reach the SOC versus the Cyber Security Team directly.' },

// ---------- Identity Protection Standard (09.03.044-4.0) ----------
{ id:'IDP-01', doc:'Identity Protection Standard', clause:'Defender for Identity', cat:'Identity & Access',
  title:'Defender for Identity is mandatory on all APM Domain Controllers',
  requires:'Microsoft Defender for Identity monitors all Active Directory activity; mandatory on all APM Domain Controllers; logs to Sentinel for SOC review and alerting.',
  scope:/domain controller|ad ds\b|active directory domain services|new (dc|domain)/i,
  test:{ kind:'mustState', pattern:/defender for identity|\bmdi\b/i },
  compensating:['no (ad ds|domain controller|active directory)','entra[- ]joined only|entra id join'],
  remedy:'Any design that stands up or touches AD DS domain controllers must include the Defender for Identity sensor on them. Cloud-native (Entra-only) designs state that no DC exists, which makes this standard not applicable.' },

// ---------- Risk Management Framework (01.01.004-8.3) ----------
{ id:'RMF-01', doc:'Risk Management Framework', clause:'\u00a73.3 Risk Assessment / Appendices A-D', cat:'Governance',
  title:'Risk assessments use the APM methodology: likelihood, consequence, controls, residual rating',
  requires:'Risks are analysed with the APM likelihood scale (Rare to Almost Certain, 1-5), consequence table (Insignificant to Severe, 1-5), inherent rating from the matrix, control effectiveness rating, and a residual rating mapped back to the matrix (Negligible / Minor / Moderate / High / Extreme).',
  scope:/risk register|risk assessment|residual risk|inherent risk/i,
  test:{ kind:'mustState', pattern:/likelihood|consequence|residual/i },
  compensating:[],
  remedy:'Rate each register entry with likelihood and consequence on the APM 1-5 scales and state the residual rating after controls, so the register can transfer into Clew without re-assessment.' },

{ id:'RMF-02', doc:'Risk Management Framework', clause:'\u00a73.4 Risk Evaluation / Appendix E', cat:'Governance',
  title:'High and Extreme residual risks need treatment plans and named acceptance authority',
  requires:'Extreme and High residual risks are generally not acceptable: treatment to a target rating within an agreed timeframe. Acceptance of Extreme only by the Board, High only by the ARC, Moderate by the responsible Executive, Minor by the business unit head. Every risk has an owner and appears in a risk register.',
  scope:/accepted risk|risk acceptance|extreme risk|high risk|risk treatment/i,
  test:{ kind:'mustState', pattern:/owner|accept(ed|ance) by|treatment|target (rating|risk)/i },
  compensating:[],
  remedy:'Name the risk owner and the acceptance authority matching the residual rating (Board for Extreme, ARC for High, Executive for Moderate). An untreated High risk without ARC acceptance cannot ship.' }
];
